### ISSUE TITLE
Open or private repo

### ISSUE THREAD

**Issue by gotom22** [ITHIM/ITHIM-R#10]
for certain (minor?) reasons it may be desirable to keep the repo private during the main project duration (e.g. first half 2018)
- could post gotomeeting link on wiki
- would not risk strangers to interfere with discussions, contents
- could (more easily?) link to GDrive contents using links

**Comment by markotainio** [comment]
I would keep this open. If we now treat this closed one, we will face a problem when we want to return to open one (or we need to create new repository for open model).

**Comment by gotom22** [comment]
good point.

How do you feel about posting the gotomeeting link, gdrive links etc. Any concerns? Trial and error? Total no go?

**Comment by markotainio** [comment]
Gdrive, dropbox etc. links I would not post here (I would use relative links describing where in Gdrive the data is). GoToMeeting - not sure if link alone will enable anything. Any experience on this?
