### ISSUE TITLE
Create a unified injury model taking data from all cities

### ISSUE THREAD

**Issue by usr110** [ITHIM/ITHIM-R#104]
Since we have limited data for injuries for each city, the current model (which is city specific) does not able to produce confidence interval, and may even have spurious predicted counts. One solution proposed by @chjackson is to create a unified model that takes data from all cities, and then used to predict counts for the baseline + scenarios.

**Comment by usr110** [comment]
The https://github.com/ITHIM/ITHIM-R/commit/4321d42ace0b2b7a17b612f8a7a3489ce0f28229 code creates a unified `poisson` model _only_ for the Who-Hit-Whom matrices (where both `casualty` and `strike` modes are known). The same can be created for NOV matrices.

@AnnaKS123

**Comment by AnnaKS123** [comment]
After many attempts to create one injury model for all cities it was decided that this is not a viable solution as the model's predictions of the baseline values of many cities are to poor.
