### ISSUE TITLE
Fix missing cas_names by replacing it with cas_modes for Injury calculations

### ISSUE THREAD

**Issue by usr110** [ITHIM/ITHIM-R#138]
@AnnaKS123 , think you accidently deleted the code without updating the subsequent lines for `cas_names`

https://github.com/ITHIM/ITHIM-R/commit/9701aeb9be1d2b52e5d0e9b561ff5c3ff4b3700d

`cas_modes` should have replaced `cas_names`. For instance here: https://github.com/ITHIM/ITHIM-R/commit/9701aeb9be1d2b52e5d0e9b561ff5c3ff4b3700d#diff-9404a1139e97c68fdbd329cff34c678fd322694f67b99d4fa1302f7cfdea16b6L130

Isn't that right?

**Comment by AnnaKS123** [comment]
@usr110 , hi, yes, sorry. I only saw that the definition for cas_mode and cas_names was identical but didn't notice that there were actually different variable names.
