### ISSUE TITLE
Travel mode definitions

### ISSUE THREAD

**Issue by gotom22** [ITHIM/ITHIM-R#14]
Relates to all aspects of 
- identifying travel mode definitions used in various sources/surveys
- standardizing/harmonizing different definitions
- defining a final "maximum set" of mode definitions used in ITHIM calculations
- defining a final "small set" of mode definitions used in ITHIM development, or use cases with sparser data

I assign to folks with good sense for local travel surveys. For starters I suggest to paste mode definitions below.

**Comment by gotom22** [comment]
**Examples**

Mode definitions in Source (Swiss travel survey):

1 | Zu Fuss
-- | --
2 | Velo
3 | Mofa,   Motorfahrrad
4 | Kleinmotorrad   (ab 16 J.)
5 | Motorrad   als Fahrer
6 | Motorrad   als Mitfahrer
7 | Auto   als Fahrer
8 | Auto   als Mitfahrer
9 | Bahn/Zug
10 | Postauto
11 | Bus/Schulbus
12 | Tram/Metro
13 | Taxi
14 | Reisecar
15 | Lastwagen
16 | Schiff,   Boot
17 | Flugzeug/Luftfahrzeug
18 | Zahnradbahn,   Standseilbahn, Seilbahn, Sessellift, Skilift
19 | Fahrzeugähnliche   Geräte
20 | E-Bike   ohne Kontrollschild
21 | E-Bike   mit gelbem Kontrollschild
95 | Anderes

Mode definitions in HEAT tool: 

Active modes
--
Walking
Cycling
Other (other active modes not implemented currently)
(Running)
(E-biking or pedelec)
(Bikesharing)

Motorized modes
--
No   data
Basic   categories
Refined   categories
--
Driving
Public   transport
Car (driver)
Car   (passenger)
Motorcycle
Local bus
Lightrail
Train

**Comment by gotom22** [comment]
Should include ICD-10 injury codes, and generally used definitions in crash data registries.

**Comment by AnnaGoodman1** [comment]
UK national travel survey, for main mode of trip:


1 | Walk, less than 1 mile
-- | --
2 | Walk, 1 mile or more
3 | Bicycle
4 | Private (hire) bus
5 | Household car - driver
6 | Non-household car - driver
7 | Household car - passenger
8 | Non-household car - passenger
9 | Household motorcycle - driver
10 | Non-household motorcycle - driver
11 | Household motorcycle - passenger
12 | Non-household motorcycle - passenger
13 | Household van/lorry - driver
14 | Non-household van/lorry - driver
15 | Household van/lorry - passenger
16 | Non-household van/lorry - passenger
17 | Other private transport
18 | London stage bus
19 | Other stage bus
20 | Public express bus/coach
21 | Excursion/tour bus
22 | London Underground
23 | Surface Rail
24 | Light rail
25 | Air
26 | Taxi
27 | Minicab
28 | Other public transport

**Comment by markotainio** [comment]
ICD-10 code have two classifications of modes, long and short. Long is used for victim, and short for cause of the injury (striking vehicle in ITHIM terminology).

Long version (ICD have fatalities for these categories):
- V01-V09 **Pedestrian** injured in transport accident
- V10-V19 **Pedal cyclist** injured in transport accident  
- V20-V29 **Motorcycle rider** injured in transport accident
- V30-V39 **Occupant of three-wheeled motor vehicle** injured in transport accident
- V40-V49 **Car occupant** injured in transport accident
- V50-V59 **Occupant of pick-up truck or van** injured in transport accident
- V60-V69 **Occupant of heavy transport vehicle** injured in transport accident
- V70-V79 **Bus occupant** injured in transport accident
- V80-V89 **Other land transport** accidents
- V90-V94 **Water transport** accidents
- V95-V97 **Air and space transport** accidents
- V98-V99 **Other and unspecified transport** accidents

More details on these groups in this file (Google drive):
https://drive.google.com/open?id=1-pSHse3Vl2gNQ9YI37rj_kIBEJi8pmn6JVuaZtMe7-Q

The short version is the striking vehicle side. For example, for Pedestrian these are:
- V01 Pedestrian injured in collision with **pedal cycle**  
- V02 Pedestrian injured in collision with **two- or three-wheeled motor vehicle**  
- V03 Pedestrian injured in collision with **car, pick-up truck or van**  
- V04 Pedestrian injured in collision with **heavy transport vehicle or bus**  
- V05 Pedestrian injured in collision with **railway train or railway vehicle**  
- V06 Pedestrian injured in collision with **other nonmotor vehicle**  
- V09 Pedestrian injured in **other and unspecified transport accidents**  

---
Aggregating long one to short ones should be doable. Main challenge is railway vehicle (short version), which isn't included in long version as own category. This will likely include e.g. metro and trams.

More info on ICD codes:
http://apps.who.int/classifications/icd10/browse/2016/en#/V80-V89

Details on classification:
http://apps.who.int/classifications/apps/icd/icd10online2004/defs.htm

**Comment by markotainio** [comment]
In Global Burden of Disease 2016 data transport injuries are provided for following modes:
**Pedestrian**   road injuries
**Cyclist**   road injuries
**Motorcyclist**   road injuries
**Motor   vehicle** road injuries
**Other road**   injuries
**Other   transport** injuries

Source:
http://ghdx.healthdata.org/gbd-results-tool

**Comment by markotainio** [comment]
ICD codes used in GBD classification are following:

Mode | ICD10 | ICD9
-- | -- | --
Road   injuries | V01-V04.9,   V06-V80.9, V82-V82.9, V87.2-V87.3 |  
Pedestrian   road injuries | V01-V04.9,   V06-V09.9 |  
Cyclist   road injuries | V10-V19.9 |  
Motorcyclist   road injuries | V20-V29.9 |  
Motor   vehicle road injuries | V30-V79.9,   V87.2-V87.3 |  
Other road   injuries | V80-V80.9,   V82-V82.9 |  
Other   transport injuries | V00-V00.8,   V05-V05.9, V81-V81.9, V83-V86.9, V88.2-V88.3, V90-V98.8 | E800-E807,   E830-E838, E840-E849

Source:
http://ghdx.healthdata.org/record/global-burden-disease-study-2016-gbd-2016-causes-death-and-nonfatal-causes-mapped-icd-codes

**Comment by robj411** [comment]
The complete list for the injuries module, following the ICD10 codes, is:

pedestrian
cyclist
motorcycle driver
three-wheeler driver
car driver
van driver
bus driver
hgv driver
motorcycle passenger
three-wheeler passenger
car passenger
van passenger
bus passenger
hgv passenger

A good list is:

pedestrian
cyclist
motorcycle driver
three-wheeler driver
car driver
van driver
motorcycle passenger
three-wheeler passenger
car passenger
bus passenger

Where we are not interested in details of the striking vehicle, and we use vehicle data to define striker exposure, we need only:

pedestrian
cyclist
motorcycle
three-wheeler
car
van
bus
hgv

**Comment by robj411** [comment]
For Accra, we define minimum five modes from the travel survey:
car
taxi
walking
bus
bicycle

And can include in addition:
motorcycle
bus_driver
truck
walk_to_bus

We map them onto other types where necessary, mostly by pre-processing in order that the naming convention is consistent across modules. In fact, all these words have been hard-coded into ITHIM-R somewhere*, so perhaps it is a list we can build on, adaptively mapping modes if necessary further down the line.

*E.g.: (1) Each mode has a specified speed, emission factor, and distance relative to car. (2) Some modes have a ventilation rate and/or pollution exposure. (3) Currently 'walking' maps directly onto 'pedestrian' in the injury module.

**Comment by robj411** [comment]
Travel modes are defined on a per-city basis. For the modules to work together, the speeds, emission inventory, trips, and injuries should match in terms of the words (inc spelling) used to describe the modes.

There are a few requirements, e.g. 'walking' mapping to 'pedestrian'. There are a few harmonisation steps where e.g. 'cycle' becomes 'bicycle'. This could be extended with a dictionary.

Modes are grouped in prespecified ways for injury distances, based on the cities we have worked with so far (and the ICD10 codes). See https://github.com/ITHIM/ITHIM-R/blob/master/R/add_distance_columns.R and https://github.com/ITHIM/ITHIM-R/blob/master/R/distances_for_injury_function.R.
