### ISSUE TITLE
Geographical downscaling of input data

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ITHIM-R#30]
starting with @nmaizlish previous work
also consider if it can be applied to DALYs as well as deaths

**Comment by gotom22** [comment]
- are downscaling and future projection indeed closely linked issues, or can they be tackles separately? if so, split. 
- need to think of "working terminology" of these data related steps. Currently I have two modules forseen: 1. Input data, 2. data harmonization (followed by 3. Scenario definition). My sense is that downscaling falls under "data harmonization", future projection under "scenario definition". But I think we need some clarifications and prob. a more refined structure. Would be good to spell out the various worksteps in words, numbered list, or similar (and I would translate to flowchart). 

for me a top priority to define these workflows soon.

**Comment by JDWoodcock** [comment]
yes agreed - happy to split
