### ISSUE TITLE
Air Pollution Background Data

### ISSUE THREAD

**Issue by gotom22** [ITHIM/ITHIM-R#34]
In early May we will need to update the links to the WHO database on air quality in cities,  of which a new release is planned.

WHO’s Urban Ambient Air Pollution database of ground measurements of PM2.5/PM10 for approximately 4200 cities in 103 countries

**Comment by robj411** [comment]
See [wiki page for air pollution processing](https://github.com/ITHIM/ITHIM-R/wiki/air-pollution-process)
