### ISSUE TITLE
ITHIM-R Directory structure

### ISSUE THREAD

**Issue by gotom22** [ITHIM/ITHIM-R#40]
A first [suggestion for a comprehensive ITHIM-R directory structure](https://docs.google.com/document/d/1K1CAymRdae3Dx8ReNB6VVqFr2PbbAmaj38JCzZf1BzU/edit#heading=h.7wq46qoo7jz4) is now available for comments and suggestions. 

It is also [available on the WIKI](https://github.com/ITHIM/ITHIM-R/wiki/Directory-Structure), but I suggest to conduct an initial round of feedbacks and edits through the gdoc (comments or direct edits). 

Please ask yourselves: 
- "the code that I produce/will produce, where will it fit?"
- "am I using additional folders that should be added?" (i.e. generic R package folders, but also others)
- "does the splitting across ITHIM-R modules work for you (e.g R/ in every module) or where do you run into problems?"
- " what kind of data/ contents is your code using and producing, and where would these go?" Do we need subdirectories in data/?
- "is the hierarchy of sub-directories intuitive, useful, practical?" (i.e. should it be city>school>student or student>school>city? Or in ithim terms: Code>Module>case study, or Module>code> casestudy, or ...etc.)

etc. etc. 

@usr110 @chjackson @syounkin @BelenZapata85 @markotainio @JDWoodcock @nmaizlish   (and everyone else inclined to comment, of course!)

**Comment by gotom22** [comment]
You may assume that we will create generic R-package folders as needed once we have nailed overall structure. So no need to list these in detail quite yet. 

** Generic R-Package components**  
    Code (R/)  
    Package Metadata (DESCRIPTION)  
    Object documentation (man/)  
    Vignettes (vignettes/)  
    Testing (tests/)  
    Namespaces (NAMESPACE)  
    Data (data/)  
    Compiled code (src/)  
    Installed files (inst/)  
    _Other components_  
    User interface (shiny/)

**Comment by robj411** [comment]
The current structure is:
- functions are in R/ with one file per function and the filename the same as the function name
- data are in inst/ext/ which is subdivided into local/ and global/.
    - In global/ are the dose--response relationships and, for now at least, emissions. (These data could potentially be moved to data/ and be loaded automatically with the library.)
    - In local/ are location-specific folders, e.g. accra/. Within each folder should be the same input files.
- tests/testthat/ contains tests
- code/ contains data processing
- results/ can contain results but isn't much in use
