### ISSUE TITLE
injury imputation of missing data

### ISSUE THREAD

**Issue by JDWoodcock** [ITHIM/ITHIM-R#42]
@robj411  @rahulatiitd
Test impuation of data using modelled results  from settings with full who hit whom matrices to see if we can impute using a one in out approach. Test for different amounts of missing data.
So e.g. if Delhi's travel patterns were the same as Sao Paulo's then if we only had data on total number of fatalities in Delhi (or victim mode only) what pattern of striking vehicles would we expect.

**Comment by rahulatiitd** [comment]
@robj411 @JDWoodcock Related to the same issue, we need to agree upon a method to allocate striking vehicles to unknown striking vehicle cases (or hit-and-run cases). This is an important issue. In Delhi, for example, we do not know striking vehicles in 40% cases. For my thesis, I estimated striking vehicles for a specific victim type based on the share of striking vehicles in known cases. Though the distribution was divided by time of day to reflect changing traffic modes during the day.
The other method is using the hit-and-run information in STATS 19 dataset-- specifically, cases categorised as hit-and-run but the striking vehicle is reported in the data. Rob has suggested using the two methods to estimate the matrix and this becomes our uncertainty.

**Comment by robj411** [comment]
Testing in https://github.com/robj411/injury_imputation

Planning to train on 'good' cities and predict for 'bad' cities.

Cities and data: What raw data we have so far in https://github.com/robj411/injury_imputation/tree/master/raw_data:

| City | Population | Trips | Injuries |
| -- | -- | -- | -- |
|Sao Paulo|x |x |x |
|Belo Horizonte|x |x |x |
|Bogota|x |x |x |
|Santiago| | | |
|Mexico City| | | |
|Buenos Aires| | | |

**Which are the 'good' cities and 'bad' cities?**

Good:
SP, BH, and B.
With some processing, we could also include S and BA.
Further work to do on BA: can we extract more from the raw data?
Further work to do on S: how can we subset the number(s) to correspond to the right region?

Bad:
Mexico City: we're missing at least half the impacting vehicles. 

**Are there any other cities to include?**
