### ISSUE TITLE
Accra motorised vehicle distances

### ISSUE THREAD

**Issue by robj411** [ITHIM/ITHIM-R#43]
For Accra, from the travel survey, we have distances for car and taxi.

For the synthetic trips, we would like to have also motorcycle, bus driver, and truck.

For the emission calculation, we can include also 'heavy truck' and 'other'.

To simulate trips or distances, we can use ratios from Rahul's heuristic distances. The ratios, relative to cars, are as follows:
taxi: 0.04
bus: 0.12
truck: 0.09
motorcycle: 0.56
big truck: 0.21
other: 0.01

Proposal:

We start with the travel survey. This forms the synthetic trip set, which feeds directly into the injury and emission calculations. 

If we want something in the synthetic trip set that isn't already there, we add it using the given ratio to car.

If we want to include those who take the trip in the synthetic population, we assign them a participant ID and demographic information. (We could also assign them other (AT) trips.)

If we want to include those who take the trip as potentially injured but not in other BOD calculations, we assign them demographic information but not a participant ID.

The emission calculation by default uses all modes. Where the mode does not have a distance from the trip set, the ratio above is used in the calculation. We can omit these modes by setting the ratio to 0.

NB. the ratio is relative to the car distance in the baseline.

**Comment by robj411** [comment]
Update for bus travel:

baseline bus distance  =  bus to car ratio * car distance,

scenario bus distance  =  baseline bus distance * scenario bus passenger distance / baseline bus passenger distance

**Comment by rahulatiitd** [comment]
@robj411 
To convert the passenger distance by bus to vehicle distance, divide passenger distance by 45.
If using a range, use 35 to 45
Source: CIRT (2011), State Transport Undertakings, Profile & Performance 2008-09, Central Institute of Road Transport, Pune, India.
