### ISSUE TITLE
Injury health burden

### ISSUE THREAD

**Issue by robj411** [ITHIM/ITHIM-R#48]
We predict injuries as a smooth function of injuries and distance provided in data. So far, these have been fatalities only. 

How do we extrapolate fatality-only data to injury YLD burden?

Within 'injuries', we can consider mild vs serious, and/or specific types of injury (as in the GBD). Within these, there are temporary and life-long injuries.

**Comment by markotainio** [comment]
Option one is not to take YLD into account. You can convert number of deaths to YLL, and we then use this to express DALY burden.

Option two is to calculate YLL to YLD rates for country, using GBD data. Thus, we would predict YLD based on YLL (by age, gender and mode, if possible).

Option three is to do everything hard way, but I would leave that for further updates.
