### ISSUE TITLE
Age groups in the calculation

### ISSUE THREAD

**Issue by markotainio** [ITHIM/ITHIM-R#8]
Discussion on what age groups calculations should be done.

Note! ITHIM-R will first be implemented for adult population. Calculations for children will be added later.

**PM2.5 air pollution**
For PM2.5 RRs for IHD and stroke are estimated for five year age groups, starting from 25 (meaning age group 25-29). Oldest age group is 95, meaning 95+ age group. For lung cancer and COPD RRs are age non-specific.

Thus, for IHD and stroke RRs for age groups <25 = 1. Should this be also so for lung cancer and COPD? 

**Physical activity**
RRs for physical activity are for adult population without age group restrictions.

**Injury**
Need to be discussed when new injury method is known.

**Comment by JDWoodcock** [comment]
@robj411 we have some specified for injury already. I think we will need different age groups for different calculations if we can. @syounkin

**Comment by usr110** [comment]
Shouldn't the age group specified by disease burden (like GBD) taken into account? @markotainio

**Comment by robj411** [comment]
That's a good point - we can discuss on Thursday?

**Comment by markotainio** [comment]
GBD wont be the bottle neck here. Current GBD data was five year age groups until age 95+. See data here in result tool:
http://ghdx.healthdata.org/gbd-results-tool

One issue is that we don't necessary need to have same age groups e.g. in injury and air pollution calculation. For the results we want to present same age groups, but final results will be aggregated from five year age groups to something else, and what happens before that aggregation can be different for injuries and air pollution.

**Comment by robj411** [comment]
The age groups are set in two input files, and they need to match. The files are the population (which tells you age, gender and population number of the city) and the GBD data for the city's country.

For Accra the age groups are '15-49' and '50-69'.

They are matched to non-travel PA data with ages '15-55' and '56-69'.

The injury module uses the given age groups. 

The PA DR function doesn't use age. 

The AP DR function uses raw age for IHD and stroke, and doesn't use age for lung cancer and CRD.

**Comment by JDWoodcock** [comment]
There is also the issue of scenarios. More age groups allow more flexible scenarios. I would ideally like to 5 year age bands and if not then 10 year age bands. To do this we will need to deal with 1) travel surveys with small numbers, 2) injury data with insufficient events. Can @robj411 suggest ways to interpolate in these cases?

**Comment by robj411** [comment]
At present, scenario generation is age independent. So the age groups we use in the downstream analysis need not impact at all on how we treat/use age in scenario generation.

(2) Zero counts of injuries are fine in the injury regression model, as it smooths over counts, as long as there is some non-zero distance. This holds whether ages are categorical or continuous covariates in the model, though the smoothing might be stronger with continuous age.

(1) My proposal for synthetic person-level travel (constructed from raw trip-level travel) could smooth over ages, adding travel for age groups where none was observed. The processing from trip-level to person-level travel is applied to individual scenarios once they are generated.

To proceed with trip-level travel, I think we could either (a) create trips as we have done in Accra for motorcycles or (b) create a synthetic trip set.

**Comment by JDWoodcock** [comment]
thanks the scenarios will likely be age specific- speak to @usr110 about how it is done for ICT

**Comment by JDWoodcock** [comment]
i prefer the synthetic trip data if it is not too much work

**Comment by robj411** [comment]
Age categories are set in the 'population.csv' file. At present, the breaks need to match GBD age breaks.
